# Generated by Django 4.0.6 on 2022-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='avatar',
            field=models.ImageField(default='Employee_default.jpg', upload_to=''),
        ),
    ]
