# Generated by Django 4.0.6 on 2022-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='avatar',
            field=models.ImageField(default='./employees/employee_default.jpg', upload_to='./employees'),
        ),
    ]
