# Generated by Django 4.0.6 on 2022-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0002_photoblog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoblog',
            name='image',
            field=models.ImageField(default='./photo-blog/photo-blog_default.jpg', upload_to='./photo-blog'),
        ),
    ]
