# Generated by Django 4.0.6 on 2022-09-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photoblog.gallery'),
            preserve_default=False,
        ),
    ]
