# Generated by Django 4.0.6 on 2022-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0006_photos_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
