# Generated by Django 4.0.6 on 2022-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoblog', '0008_remove_gallery_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='description',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
