# Generated by Django 4.0.6 on 2022-09-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notedAchievements', models.TextField(blank=True)),
                ('servicesNotRealized', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract_price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('countryName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('minParticipants', models.IntegerField()),
                ('maxParticipants', models.IntegerField()),
                ('execution', models.CharField(blank=True, default='Guaranteed', max_length=100)),
                ('language', models.CharField(blank=True, default='Deutsch', max_length=100)),
                ('image', models.ImageField(default='./tours/tour_default.jpg', upload_to='./tours')),
                ('Service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='tours.services')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='tours.tags')),
            ],
        ),
        migrations.CreateModel(
            name='TourDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='./tour_days/tour-days_default.jpg', upload_to='./tour_days')),
                ('drivingKilometers', models.IntegerField()),
                ('driveTime', models.IntegerField()),
                ('meals', models.TextField(default='')),
                ('overnight_stay', models.CharField(max_length=255, null=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_days', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('price', models.IntegerField()),
                ('booking_remaining_places_img', models.ImageField(default='./booking/booking_default.png', upload_to='./booking')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
