# Generated by Django 4.0.6 on 2022-09-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='Service',
            new_name='service',
        ),
    ]
