# Generated by Django 4.0.6 on 2022-09-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.services'),
        ),
    ]
