# Generated by Django 4.0.6 on 2022-09-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='tour',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
            preserve_default=False,
        ),
    ]
