# Generated by Django 4.0.6 on 2022-09-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_tour_service_services_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tour',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
